### ISSUE TITLE
Recuperación de contraseña

### ISSUE THREAD

**Issue by ClusterMax** [JuanFelipeJaramillo20/launcher_backend#1]
Como usuario, deseo recuperar mi contraseña ingresando mi correo registrado, para acceder a mi cuenta en caso de olvidarla.

**Comment by JuanFelipeJaramillo20** [comment]
La funcionalidad de recuperación de contraseña para los usuarios se agrega en: https://github.com/JuanFelipeJaramillo20/launcher_backend/commit/ddca4c9f5858168b39b2ef16958af5843d1d9149
