### ISSUE TITLE
Datos el usuario

### ISSUE THREAD

**Issue by ClusterMax** [JuanFelipeJaramillo20/launcher_backend#14]
Como usuario, deseo que todos mis datos se guarden en una base de datos, para que estén disponibles en futuras sesiones.

**Comment by JuanFelipeJaramillo20** [comment]
la persistencia de datos en BD fue agregada en: https://github.com/JuanFelipeJaramillo20/launcher_backend/commit/8b53250aae469fd10e0053e6da95e868dca649c0
