### ISSUE TITLE
Servicio de correos electrónicos

### ISSUE THREAD

**Issue by ClusterMax** [JuanFelipeJaramillo20/launcher_backend#2]
Como usuario, deseo recibir correos electrónicos con diferentes fines (recuperación de contraseña, etc.)

**Comment by JuanFelipeJaramillo20** [comment]
El servicio de email fue integrado en: https://github.com/JuanFelipeJaramillo20/launcher_backend/commit/3a0d83032a55b725724b07cc13af784b8512b244
Progresivamente se añadirá código para enviar más correos en los flujos necesarios de la aplicación. Por ahora, solo se envían correos en el registro
