### ISSUE TITLE
Administrador - Estadísticas generales

### ISSUE THREAD

**Issue by ClusterMax** [JuanFelipeJaramillo20/launcher_backend#25]
Como administrador, quiero ver las estadísticas generales del servidor para monitorizar el uso del sistema y su rendimiento.

**Criterios de aceptación:**

- Se muestran gráficos con métricas del servidor (carga, usuarios conectados, transacciones).
- El administrador puede exportar el reporte en PDF.

Detalles: Consulta de datos de rendimiento del servidor y generación de PDF.

**Comment by JuanFelipeJaramillo20** [comment]
![image](https://github.com/user-attachments/assets/a3ca8263-a620-4ba2-be0b-e4811146b981)
