### ISSUE TITLE
Administrador - Gestión de usuarios

### ISSUE THREAD

**Issue by ClusterMax** [JuanFelipeJaramillo20/launcher_backend#3]
Como administrador, deseo gestionar todos los usuarios por medio de un panel de administrador, para controlar el acceso y la actividad en el sistema.

**Comment by JuanFelipeJaramillo20** [comment]
Creo que este issue debería ser mas del repo del frontend, desde el backend esta funcionalidad se soluciona con el CRUD de usuarios @ClusterMax
