### ISSUE TITLE
Administrador - Aprobación de usuarios

### ISSUE THREAD

**Issue by ClusterMax** [JuanFelipeJaramillo20/launcher_backend#4]
Como administrador, deseo aprobar el registro de nuevas cuentas, para validar y autorizar a los usuarios.

**Comment by JuanFelipeJaramillo20** [comment]
Flujo completado en: https://github.com/JuanFelipeJaramillo20/launcher_backend/commit/063ca5a288c55cb5770a7d2f99b8c6617fd0b993
